language: generic
sudo: required
services:
    - docker
before_install:
    - docker build -t melodyromero/docker-react Dockerfile.dev .
script:
    - docker run -e CI=true melodyromero/docker-react npm run test